name: quick_qr
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  mobile_scanner: ^6.0.7 #to scan bar code and qr code
  pretty_qr_code: ^3.3.0 #to get string or othr info and convert into qr code
  image_picker: ^1.1.2
  saver_gallery: ^4.0.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  image: ^4.5.2
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
   # - assets/icons/settings